// Critic agent — reviews every Correspondent draft on 4 axes
// Verdict: approve | reject | escalate_to_planner (after N iterations)
// Writes critic_reviews row and signals scored outcomes for flywheel

import { startAgentRun, endAgentRun, askClaudeJSON, logSignal } from "./shared";
import { OPUS_MODEL } from "@/services/claude";
import { restSelectOne, restSelect, restInsert, restUpdate, eq } from "@/lib/supabase-rest";
import { factCheckDraft } from "./fact-checker";
import type { CriticScores, CriticVerdict } from "@/shared/ib-types";
import type { Json } from "@/lib/database.types";

export interface CriticInput {
  draftId: string;
}

export interface CriticOutput {
  reviewId: string;
  verdict: CriticVerdict;
  scores: CriticScores;
  overallScore: number;
  feedback?: string;
  suggestedRevision?: string;
}

const MAX_ITERATIONS = 3;
const APPROVAL_THRESHOLD = 7; // per axis

const SYSTEM_PROMPT = `You are a recruiting VP reviewing a cold email a college sophomore is about to send to an investment banker. Your job is to score it on 4 axes and either approve or reject with surgical feedback.

Tonight's calibration (real banker feedback on prior drafts):
"Both read too much like 'smart networking email generated by AI' instead of 'real sophomore who noticed something specific and is easy to reply to.' Lines like 'highlights exactly the kind of analytical thinking that draws me to the field', 'the analytical side of M&A work', and 'made the transition from College Hill to finance' are dead giveaways — too generic, too vague, no genuine connection. Feels stalky and could be sent to anyone."

Fresh Architect calibration (May 4): Rice B.Arch drafts repeatedly failed by using abstract bridges like "analytical / problem-solving side of architecture" and "sequencing constraints under tight reviews." A good non-finance bridge names one concrete class/project artifact first, then ties it to one verified banker/firm anchor.

So: be ruthless on AI-tells. The bar is not "polished email." The bar is "would a real curious sophomore actually write this, and would the banker want to reply?"

Axes (each 0-10):
1. Specificity — does it reference a real deal, real post, real shared experience, or real career move? Generic compliments about "your impressive career" or vague "I'm interested in M&A" = LOW. A line that engages with one concrete observable thing = HIGH. The opener is the test: could it be sent to any other banker in the group? If yes, fail.
2. Voice Match — does it sound like a 20-year-old sophomore? Plain, slightly under-polished, contractions, short sentences = HIGH. Consultant-speak, "I hope this email finds you well", "the analytical side of X work", "made the transition from X to Y", abstract takes about the industry = LOW. The student doesn't have deep industry takes yet — they shouldn't try.
3. Guardrails — no em-dashes (—). No banned words (cognizant, leverage, endeavor, synergy, furthermore, accordingly, aforementioned). 80-150 words is the target — over 180 is automatic reject. Ends with "Thanks," or "Best,". 15-min ask, not a demand. No formal "Sincerely / Regards".
4. Shared-ground anchor — does the opener actually engage with the anchor (deal, post, club, class) — or just name-drop it? "I saw you went to Brown" = LOW. "I saw your team advised on the FinservCo carve-out — curious how the team approached the regulatory side" = HIGH.

Specific banned phrases — if ANY appear, reject:
- "I hope this email finds you well"
- "highlights the kind of [X] that draws me"
- "the analytical side of [X] work"
- "analytical / problem-solving side of [X]"
- "problem-solving habits I'm building"
- "made the transition from [X] to [Y]"
- "your transition to [X]" / "your jump from [X] to [Y]" / "your path from [X] to [Y]" — any career-arc framing the student couldn't actually know
- "your impressive [career/work/background]"
- "I'm interested in [M&A / IB / finance]" (must be more concrete)
- Any em-dash

FABRICATION CHECK — this is the highest-priority axis. Score 0 and reject if ANY specific claim in the email is not literally present in the banker data provided:
- Any "your post about ..." — must match a verbatim recent_post in the data
- Any "your team advised on ..." or "your work on the X deal" — must appear in deal_areas or recent_deals_mentioned
- Any quote from the banker — must be verbatim in about_section or recent_post
- Any specific career detail (role at firm X for Y years, school activity, etc.) — must be in the data
If you see a specific claim and the data is empty or doesn't contain it, REJECT with "fabricated_claim". The student would rather send a short honest email than a fabricated specific one. Bankers spot fabrications instantly.

Rules:
- If ANY axis scores below 7, verdict = reject. Give surgical feedback on the weakest axis with a "try this" one-liner.
- Don't be nice. Be the reviewer these students need.
- If all axes ≥ 7, verdict = approve.
- feedback: 1-3 sentences, actionable.
- suggestedRevision (optional): if you can quickly rewrite the opener or subject to fix the weakest axis, include it verbatim.`;

export async function runCritic(input: CriticInput): Promise<CriticOutput> {
  const draft = await restSelectOne("drafts", {
    select: "*",
    filters: { id: eq(input.draftId) },
  });
  if (!draft) throw new Error("Draft not found");

  const ctx = await startAgentRun({
    agent: "critic",
    userId: draft.user_id,
    triggeredBy: "agent_dispatch",
    inputSummary: { draftId: input.draftId, iteration: draft.iteration_count },
  });

  try {
    // Pre-flight fact-check: web-search every specific claim before scoring.
    // If anything fabricated slips past the LLM critic, this rejects it
    // deterministically. Skipped for non-cold/followup types (replies +
    // thank-yous reference the prior conversation, not net-new claims).
    if (draft.type === "cold" || draft.type === "followup") {
      const banker = await restSelectOne("bankers", {
        select: "id, name, title, firm_id, linkedin_url, university",
        filters: { id: eq(draft.banker_id ?? "") },
      });
      if (banker) {
        const [firm, profile, findings] = await Promise.all([
          banker.firm_id
            ? restSelectOne("firms", { select: "name", filters: { id: eq(banker.firm_id) } })
            : Promise.resolve(null),
          // Pull the curator-synthesized about_section so the fact-checker
          // can short-circuit on claims already grounded in our own data.
          // Without this, niche-but-real facts (e.g. Harvard PCG roundtable
          // participant lists on .edu pages) get rejected because Serper
          // can't re-verify them.
          restSelectOne("banker_profiles", {
            select: "about_section",
            filters: { banker_id: eq(banker.id as string) },
          }),
          // Underlying findings — passed into fact-checker so when the
          // about_section short-circuit fires, evidenceUrls get populated
          // with the actual source URLs (Harvard PCG list, Crunchbase
          // page, FINRA broker page, etc.). Without this, the /today UI's
          // "Sources" disclosure stays empty and the user can't verify
          // niche-looking claims before hitting Send.
          restSelect("banker_findings", {
            select: "url, title, snippet",
            filters: { banker_id: eq(banker.id as string) },
            limit: 20,
          }),
        ]);
        let factCheck;
        try {
          factCheck = await factCheckDraft(draft.body as string, {
            name: banker.name as string,
            title: banker.title as string | null,
            firmName: (firm?.name as string | undefined) ?? null,
            linkedinUrl: banker.linkedin_url as string | null,
            university: banker.university as string | null,
            aboutSection: (profile?.about_section as string | null) ?? null,
            findings: (findings ?? []).map((f) => ({
              url: f.url as string,
              title: (f.title as string | null) ?? null,
              snippet: (f.snippet as string | null) ?? null,
            })),
          });
        } catch (err) {
          // Fact-check extraction itself failed — Claude returned malformed
          // JSON or refused. This is the failure mode where a draft would
          // otherwise pass unchecked. Route to needs_revision instead so
          // the draft isn't silently approved.
          await logSignal({
            userId: draft.user_id as string,
            bankerId: draft.banker_id as string | null ?? undefined,
            draftId: draft.id as string,
            agent: "critic",
            signalType: "fact_check_unavailable",
            metadata: { error: String(err).slice(0, 200) },
          });
          const review = await persistReview({
            draftId: draft.id as string,
            scores: { specificity: 5, voiceMatch: 6, guardrails: 6, sharedGround: 5 },
            overallScore: 5.5,
            verdict: draft.iteration_count + 1 >= MAX_ITERATIONS ? "escalate_to_planner" : "reject",
            feedback: "Fact-check service couldn't run cleanly. Re-drafting with safer (less specific) claims so we can verify before send.",
          });
          await advanceDraftStatus(draft.id as string, review.verdict);
          await endAgentRun(ctx, { verdict: review.verdict, reason: "fact_check_unavailable" });
          return review;
        }
        // Persist the fact-check on the draft so /today can show citations
        // under the email body. Stored even when ok — verified claims with
        // their sources are useful proof to the user.
        await restUpdate(
          "drafts",
          { fact_check: factCheck as unknown as Json },
          { id: eq(draft.id) }
        );
        const fabricated = factCheck.checks.filter((c) => c.verdict !== "verified");
        if (fabricated.length > 0) {
          const review = await persistReview({
            draftId: draft.id,
            scores: { specificity: 4, voiceMatch: 6, guardrails: 6, sharedGround: 3 },
            overallScore: 4.75,
            verdict: draft.iteration_count + 1 >= MAX_ITERATIONS ? "escalate_to_planner" : "reject",
            feedback: `Fabrication risk: ${fabricated.length} claim(s) couldn't be verified online. ${fabricated.map((c) => `"${c.claim.slice(0, 60)}"`).join("; ")}. Rewrite without those specifics — lean on school/firm/group anchors instead.`,
          });
          await advanceDraftStatus(draft.id, review.verdict);
          await endAgentRun(ctx, { verdict: review.verdict, reason: "fact_check_fail", unverifiedClaims: fabricated.length });
          return review;
        }
      }
    }

    // Hard auto-reject if guardrails blocked the draft
    const flags = (draft.guardrail_flags ?? {}) as Record<string, unknown>;
    const bannedPhrases = Array.isArray(flags.bannedPhrasesFound) ? (flags.bannedPhrasesFound as string[]) : [];
    const tooShort = Boolean(flags.tooShort);
    const tooLong = Boolean(flags.tooLong);

    if (bannedPhrases.length > 0 || tooShort || tooLong) {
      const guardrailScore = bannedPhrases.length > 0 ? 2 : tooShort ? 4 : 5;
      const review = await persistReview({
        draftId: draft.id,
        scores: { specificity: 5, voiceMatch: 5, guardrails: guardrailScore, sharedGround: 5 },
        overallScore: (5 + 5 + guardrailScore + 5) / 4,
        verdict: draft.iteration_count >= MAX_ITERATIONS ? "escalate_to_planner" : "reject",
        feedback: [
          bannedPhrases.length > 0 ? `Banned phrases detected: ${bannedPhrases.join(", ")}` : null,
          tooShort ? "Email is too short — should be 100-180 words" : null,
          tooLong ? "Email is too long — trim to 100-180 words" : null,
        ]
          .filter(Boolean)
          .join(". "),
      });
      await advanceDraftStatus(draft.id, review.verdict);
      await endAgentRun(ctx, { verdict: review.verdict, reason: "guardrail_hard_fail" });
      return review;
    }

    // The Critic needs to know what's in our DB so it can distinguish
    // "fabricated by the LLM" from "true and we already have it." Without
    // this, claims like "you went to Rice" get flagged as fabrications even
    // when banker.university IS Rice in the DB. Pull a minimal banker
    // context once for the LLM-scoring step.
    //
    // Also surface the curator-synthesized about_section. Without it, the
    // LLM Critic flags real grounded claims (Robert Ragland co-founded
    // Carter & Clyde — sourced from Crunchbase finding, captured in
    // synthesis) as fabrication risk because they're not in the minimal
    // structured fields above. Same gap the fact-checker had — fixed there
    // in 15030a4/55db36e, this is the LLM-Critic equivalent.
    const [bankerForCritic, profileForCritic] = draft.banker_id
      ? await Promise.all([
          restSelectOne("bankers", {
            select: "name, title, university, grad_year, firm_id, linkedin_url",
            filters: { id: eq(draft.banker_id) },
          }),
          restSelectOne("banker_profiles", {
            select: "about_section",
            filters: { banker_id: eq(draft.banker_id) },
          }),
        ])
      : [null, null];
    const firmForCritic = bankerForCritic?.firm_id
      ? await restSelectOne("firms", { select: "name", filters: { id: eq(bankerForCritic.firm_id) } })
      : null;
    const aboutForCritic = (profileForCritic?.about_section as string | null) ?? null;
    const knownFactsBlock = bankerForCritic
      ? `KNOWN BANKER FACTS (these are NOT fabrications — our DB has them. Do NOT flag the email for stating them):
- Name: ${bankerForCritic.name}
- Title: ${bankerForCritic.title}
- Firm: ${firmForCritic?.name ?? "(unknown)"}
- University: ${bankerForCritic.university ?? "(not in DB)"}
- Graduation year: ${bankerForCritic.grad_year ?? "(not in DB)"}
- LinkedIn: ${bankerForCritic.linkedin_url ?? "(not in DB)"}${aboutForCritic ? `

CURATOR-SYNTHESIZED ABOUT SECTION (also grounded — facts here are sourced from real findings, treat as known):
${aboutForCritic}` : ""}

`
      : "";

    const prompt = `Review this draft:

${knownFactsBlock}SUBJECT: ${draft.subject ?? "(no subject)"}

BODY:
${draft.body}

TYPE: ${draft.type} (${draft.type === "cold" ? "first-time cold outreach to this banker" : draft.type === "followup" ? "follow-up on a prior unanswered email" : draft.type === "reply" ? "response to the banker's reply" : "thank-you after a coffee chat"})

Important: Stating any of the KNOWN BANKER FACTS above (name, title, firm, university, grad year) is fine — that's data we have. Only flag if the email asserts something MORE SPECIFIC that's not in the known facts (e.g., a specific deal name, a specific post, a specific dated transition).

Return JSON:
{
  "scores": { "specificity": 0-10, "voiceMatch": 0-10, "guardrails": 0-10, "sharedGround": 0-10 },
  "overallScore": 0-10 (arithmetic mean),
  "verdict": "approve" | "reject",
  "feedback": "1-3 sentences",
  "suggestedRevision": "optional quick rewrite of the weakest part, or omit"
}`;

    const result = await askClaudeJSON<{
      scores: CriticScores;
      overallScore: number;
      verdict: "approve" | "reject";
      feedback: string;
      suggestedRevision?: string;
    }>(prompt, { systemPrompt: SYSTEM_PROMPT, maxTokens: 1024, model: OPUS_MODEL, userId: draft.user_id as string, agent: "critic" });

    const minAxis = Math.min(result.scores.specificity, result.scores.voiceMatch, result.scores.guardrails, result.scores.sharedGround);
    let verdict: CriticVerdict = minAxis >= APPROVAL_THRESHOLD ? "approve" : "reject";
    if (verdict === "reject" && draft.iteration_count + 1 >= MAX_ITERATIONS) {
      verdict = "escalate_to_planner";
    }

    const review = await persistReview({
      draftId: draft.id,
      scores: result.scores,
      overallScore: result.overallScore,
      verdict,
      feedback: result.feedback,
      suggestedRevision: result.suggestedRevision,
    });
    await advanceDraftStatus(draft.id, verdict);

    await logSignal({
      userId: draft.user_id,
      bankerId: draft.banker_id ?? undefined,
      draftId: draft.id,
      agent: "critic",
      signalType: `critic_${verdict}`,
      metadata: { overallScore: result.overallScore, axes: result.scores, iteration: draft.iteration_count },
    });

    await endAgentRun(ctx, { verdict, overallScore: result.overallScore });
    return review;
  } catch (err) {
    await endAgentRun(ctx, {}, String(err));
    throw err;
  }
}

async function persistReview(opts: {
  draftId: string;
  scores: CriticScores;
  overallScore: number;
  verdict: CriticVerdict;
  feedback?: string;
  suggestedRevision?: string;
}): Promise<CriticOutput> {
  const inserted = await restInsert("critic_reviews", {
    draft_id: opts.draftId,
    scores: opts.scores as unknown as Json,
    overall_score: opts.overallScore,
    verdict: opts.verdict,
    feedback: opts.feedback,
    suggested_revision: opts.suggestedRevision,
  });
  const reviewId = inserted[0]?.id ?? "";
  if (reviewId) {
    await restUpdate("drafts", { critic_review_id: reviewId }, { id: eq(opts.draftId) });
  }

  // Snapshot the draft's current body+verdict into draft_iterations so we
  // preserve every revise step. Without this, the iter 0 and iter 1 bodies
  // are lost when the Correspondent UPDATEs the row in place. Subsequent
  // iterations of Correspondent now have access to their own past attempts.
  const draft = await restSelectOne("drafts", {
    select: "subject, body, guardrail_flags, fact_check, iteration_count",
    filters: { id: eq(opts.draftId) },
  });
  if (draft) {
    await restInsert("draft_iterations", {
      draft_id: opts.draftId,
      iteration: draft.iteration_count,
      subject: draft.subject,
      body: draft.body,
      guardrail_flags: draft.guardrail_flags,
      fact_check: draft.fact_check,
      critic_review_id: reviewId || null,
      critic_verdict: opts.verdict,
      critic_feedback: opts.feedback ?? null,
      critic_score: opts.overallScore,
    });
  }

  return {
    reviewId,
    scores: opts.scores,
    overallScore: opts.overallScore,
    verdict: opts.verdict,
    feedback: opts.feedback,
    suggestedRevision: opts.suggestedRevision,
  };
}

async function advanceDraftStatus(draftId: string, verdict: CriticVerdict): Promise<void> {
  const newStatus =
    verdict === "approve" ? "approved" :
    verdict === "escalate_to_planner" ? "rejected_unresolvable" :
    "needs_revision";
  await restUpdate("drafts", { status: newStatus, updated_at: new Date().toISOString() }, { id: eq(draftId) });
}
